apiVersion: v1
kind: PersistentVolume
metadata:
  name: volname
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data/
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tf-hub-lb-katacoda
  name: tf-hub-lb-katacoda
spec:
  type: LoadBalancer
  ports:
  - name: hub
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: tf-hub
  externalIPs:
  - $HOST_IP
  - $HOST2_IP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: centraldashboard-katacoda
  name: centraldashboard-katacoda
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: centraldashboard
  externalIPs:
  - $HOST_IP
  - $HOST2_IP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador-katacoda
spec:
  type: LoadBalancer
  ports:
  - name: ambassador
    port: 30080
    protocol: TCP
    targetPort: 80
  selector:
    service: ambassador
  externalIPs:
  - $HOST_IP
  - $HOST2_IP
